// File generated by hand from google-services.json (com..japanfuturemap)
// Project: apps2-752cb・・OS迚医→邨ｱ荳縲ゆｻ悶い繝励Μ縺ｨ蜈ｱ逕ｨ縺ｮFirebase繝励Ο繧ｸ繧ｧ繧ｯ繝茨ｼ・

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run flutterfire configure to add a web app if needed.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqvvJcP4lPYv811PNvs1TptSIhtHupjFY',
    appId: '1:946448575860:android:e82c933388f25e3a37d021',
    messagingSenderId: '946448575860',
    projectId: 'apps2-752cb',
    storageBucket: 'apps2-752cb.firebasestorage.app',
  );

  // iOS迚医・Android迚医→繧ゅ↓apps2-752cb・井ｻ悶い繝励Μ縺ｨ蜈ｱ逕ｨ縺ｮFirebase繝励Ο繧ｸ繧ｧ繧ｯ繝茨ｼ峨↓邨ｱ荳縲・
  // OS髢薙〒Firestore繝・・繧ｿ・域兜逾ｨ繝ｻ繧ｳ繝｡繝ｳ繝医・謠先｡育ｭ会ｼ峨′蜈ｱ譛峨＆繧後ｋ・・026-07-27邨ｱ荳・峨・
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4gaFcLxN8iT7xm6JeIM7Iou-efE5g5SM',
    appId: '1:946448575860:ios:0fd631a6510c7fab37d021',
    messagingSenderId: '946448575860',
    projectId: 'apps2-752cb',
    storageBucket: 'apps2-752cb.firebasestorage.app',
    iosBundleId: 'com..japanfuturemap',
  );
}

